# Course configuration
course_title: 'COS518: Advanced Computer Systems'
course_year: 2017
course_term: Spring
directory:
  - name: 'home'
    path: '/'
  - syllabus
  - projects
  - name: 'piazza'
    path: 'https://piazza.com/princeton/spring2017/cos518'

# Jekyll configuration
markdown: kramdown
