# Course configuration
course_title: 'COS518: Advanced Computer Systems'
course_year: 2018
course_term: Spring
directory:
  - name: 'home'
    path: 'index.html'
  - syllabus
  - projects
  - name: 'piazza'
    path: 'https://piazza.com/princeton/spring2018/cos518'

# Jekyll configuration
markdown: kramdown
